# Generated by Django 5.1.7 on 2025-04-04 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comments", "0001_initial"),
        ("Likes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Comments.comment",
            ),
        ),
    ]
