# Generated by Django 5.1.7 on 2025-03-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Video", "0002_video_is_public_video_slug_video_tags_video_views_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
